Repository RedHat-SP-Security/tests, pull requests merged in 2020-11, with the labels that each got.

#9 rsyslog/multihost/rsyslog send messages to remote
  rsyslog/Multihost/rsyslog-send-messages-to-remote/TC#0167027.fmf
  rsyslog/Multihost/rsyslog-send-messages-to-remote/TC#0167028.fmf
  rsyslog/Multihost/rsyslog-send-messages-to-remote/main.fmf
Labels: Metadata

#12 pin-sss
  clevis/Sanity/pin-sss/runtest.sh
Labels: Fix

#10 usbguard-1.0 rebase coverage
  usbguard/Sanity/1738590-rebase-usbguard-to-0.7.8/Makefile
  usbguard/Sanity/1738590-rebase-usbguard-to-0.7.8/base.fmf
  usbguard/Sanity/1738590-rebase-usbguard-to-0.7.8/main.fmf
  usbguard/Sanity/1738590-rebase-usbguard-to-0.7.8/one_paramater.fmf
  usbguard/Sanity/1738590-rebase-usbguard-to-0.7.8/runtest.sh
  usbguard/Sanity/config-sanity/Makefile
  usbguard/Sanity/config-sanity/base.fmf
  usbguard/Sanity/config-sanity/main.fmf
  usbguard/Sanity/config-sanity/rule_options.fmf
  usbguard/Sanity/config-sanity/runtest.sh
Labels: Functional, Scope
